main: real.peha.fun.WorldsPlugin
name: WorldsPlugin
version: 0.1
author: RealPeha
api-version: 1.16

commands:
  jopa:
    usage: /<command> [reload]

permissions:
  worldsplugin.*:
    description: Дает доступ ко всем командам WorldsPlugin
    default: false
    children:
      worldsplugin.reload: true
  worldsplugin.reload:
    description: Дает доступ к команде /rp reload
    default: op
