main: real.peha.fun.WorldsPlugin
name: WorldsPlugin
version: 0.1
author: RealPeha
api-version: 1.16

commands:
  world:
    aliases: wr
    usage: /<command> [reload|create|delete|info|load|unload|list|bed]

permissions:
  worldsplugin.usage:
    description: Дает доступ ко всем командам WorldsPlugin
    default: op
  worldsplugin.enter:
    description: Дает право на вход в миры
    default: op
